# Backend Dockerfile - Node.js
FROM node:18-alpine
WORKDIR /usr/src/app
COPY ./backend/package.json ./backend/package-lock.json* /usr/src/app/
RUN npm install --production
COPY ./backend /usr/src/app
EXPOSE 3000
CMD ["node", "server.js"]
